name: GitHub Actions Demo
run-name: Building and Deploying Documentation 🚀
on: [push]
jobs:
  build-docs:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y
        shell: bash

      - name: Add Better Syling
        run: |
          cd Docs
          git submodule add https://github.com/jothepro/doxygen-awesome-css.git
          cd doxygen-awesome-css
          git checkout v2.3.3
          cd ..
          ls
          cd ..

      - name: Generate Doxygen Documentation
        run: doxygen Docs/vmsDoxyfile.in
        shell: bash

      # - name: Add text to file
      #   run: echo "// This is some text comment" >> Docs/html/navtreedata.js
      #   shell: bash
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Docs/html # The folder the action should deploy.
